version: '3.1'

services:
  php:
    build: .
    ports:
      - 8081:80
   


  db:
    image: mariadb
    restart: always
#    command: --default-authentication-plugin=mysql_native_password
    environment: 
#        MYSQL_ROOT_PASSWORD: p@ssw0rD
#        MYSQL_USER: php   
     - ALLOW_EMPTY_PASSWORD=yes

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports: 
      - 8888:80
    environment:
      - PMA_ARBITRARY=1 
  
  
  
